---
title: "SPGA Student Support Handbook 2025/26"
format:
  html:
    toc: true
    number-sections: false
  pdf:
    toc: true
---

This handbook provides information about the support services available to SPGA students for the 2025/26 academic year. If you feel any important details are missing, please don’t hesitate to reach out by emailing [Zahra.gambarova@city.ac.uk](mailto:Zahra.gambarova@city.ac.uk).

# General information
[Navigating Campus](https://studenthub.city.ac.uk/information-technology/citynav): Download and use the [CityNav](https://studenthub.city.ac.uk/information-technology/citynav) app.
[Term Dates](https://www.city.ac.uk/about/vision-and-strategy/academic-excellence/education/academic-year-and-term-dates)
[Timetable Information](https://mytimetable.city.ac.uk/)   Record their attendance at all timetabled activities on campus using [Count Me In](https://www.youtube.com/watch?v=2a_qMAZ4m2w). You can view your timetable and keep track of your attendance all in one place with the [SEAtS Mobile app](https://studenthub.citystgeorges.ac.uk/academic-resources/learning-and-study-support/study-skills-and-support/attendance-and-engagement/count-me-in).
[Student Guides to Educational Technology](https://city-uk-ett.libguides.com/student)  Guidance on the use of educational technology at City St Georges, such as Moodle, Microsoft teams, etc., is available here.
[AppsAnywhere](https://studentcommunications.newsweaver.com/1w52bcjsfr/18i0udma1fv/external?a=6&p=4118384&t=27571) – an app store-style platform where you can access most City St George's apps.
[GetHeard@City](https://city.unitu.co.uk/Account/Login) is a digital platform for student voice that students can use to ask questions to your Programme Reps, discuss your experiences with other students, and give feedback to the Students’ Union and University staff.
[Instagram](https://www.instagram.com/spga.citystgeorges/) Follow @[SPGA.CityStGeorges](https://www.instagram.com/spga.citystgeorges/) on Instagram to stay updated on upcoming events and opportunities.

# Essentials of Students’ Conduct and Behaviour in the Classroom

## General conduct
Behave professionally – be punctual, engaged and nondisruptive in all teaching and learning sessions.
Respect the physical and digital environment of the institution and our local community.
Behave responsibly and respectfully.
Be aware that people come from different backgrounds and cultures.
Treat fellow students, staff and visitors with respect.
Behave collaboratively and collegially in shared spaces – classrooms, library, computer rooms and online spaces.

## Attendance
It is in your interests to attend; you will gain far more from your university experience if you attend classes and engage with your studies, your tutors and your classmates. There is clear evidence that those who attend classes get better results.
It is also worth noting that your attendance / engagement record may be requested as part of a reference.
Attendance at classes is monitored; both so that we can comply with UKVI requirements, for students on visas, and to help us identify students who may need support.
We won’t ask you to explain every absence but we will contact you if your attendance / engagement raises concerns about your wellbeing.
Remember to take your student card to class so that you can ‘tap in’.
Do not “tap into” a class and then leave before it begins or not long into it, just to get your attendance recorded.
This disturbs classes and does not benefit you in any way. It is also dishonest.
We conduct manual checks of electronic attendance records and, if you are found to be falsifying your record in this way, you could be subject to a disciplinary investigation.
If you can’t stay for the whole class, leave during the break, rather than disturbing others.
Remember all lectures are recorded so, if you can’t attend, you can watch it at a more convenient time.
If you cannot attend a small group class for some good reason you should request to attend an alternative class, where this is available. Contact your lecturer or course office for more information.
Arrive on time for all your scheduled classes. Be present and in a seat, ready to begin the class at the scheduled start time. If there is a break, return promptly.
If you are late:
Enter as quietly as possible, and take the closest available seat so that you minimise the disturbance to others.
In a lecture theatre, use the rear entrance, where available.

## Classroom engagement
Prepare the work set.
Whether this is reading and / or carrying out specific exercises, if you have not prepared you will not get the full benefit from the class.
Being prepared benefits your group; for example, ensuring there is active discussion; or that you all play your part in the skills based classes.
If you cannot prepare, for some good reason, you should let your tutor know. This may prevent you from being put on the spot when called upon to answer a question which you do not know the answer to.
Engage with the class by:
Taking part in any polls or quizzes / questions set by the tutor.
Taking an active part in the smaller group classes. Join in with group discussions; answer the questions asked of you; listen and pay attention.
If you were not able to prepare fully, or at all, pay close attention; answer or discuss any aspect you are able to. Often you will find you can take a more active part than you thought.
Don’t talk during class, unless you are participating in the class.
This is a distraction to other students who want to listen to the class and gain the benefit from it. You will not learn from the class if you’re talking about something else.

## Email communication
Email is our primary means of communication with you; make sure you check your City St George’s email several times a day, especially first thing in the morning, in case there are any last minute changes to your timetable due to staff illness.
Remember that email is a formal means of communication:
Address all members of our community politely and formally.
When emailing City St Georges staff, please include your student ID, course name and subject of query, this helps us to find you on the system and resolve your query quickly.
Do not say something in an email or message that you would not say to that person’s face, or in a way that you would not want to be addressed yourself.
Remember that humour or sarcasm can easily be misunderstood, especially when not accompanied by facial expressions or body language.
Remember that most staff work 9-5 Monday-Friday so you are should not expect to receive a response outside these times.

# Assessment information
Assessment Dates will be available within your Moodle Module pages, and exam dates can also be found from [https://studenthub.city.ac.uk/timetabling-term-dates-exams/exams/exam-timetable](https://studenthub.city.ac.uk/timetabling-term-dates-exams/exams/exam-timetable).

Late submission policy for coursework: Any work that is submitted more than 1 minute past the deadline but within 48 hours will have 10 marks deducted as a penalty. Work submitted after 48 hours will receive a zero.

​​​​​​​If you are not able to complete an assessment by the deadline there are two different options in SPGA:
- [Extensions](https://cityuni.sharepoint.com/teams/CUoL-SASSStudentSupport/SitePages/SASS-Extensions.aspx) - can be used when you need up to 1 week extra to complete coursework.
- [Extenuating Circumstances](https://cityuni.sharepoint.com/teams/CUoL-SASSStudentSupport/SitePages/SASS-Extensions.aspx) - are for when you cannot take an examination or assessment by the time of the deadline. By applying for an EC, you apply for a deferment of the assessment to the next available assessment period (normally, that would be the resit period in summer).  Apply for Extenuating Circumstances via [eVision](https://evision.city.ac.uk/) no later than 7 days after your assessment deadline

[Academic Misconduct](https://studenthub.city.ac.uk/help-and-support/academic-integrity-and-misconduct) – is any action that produces or seeks to produce an improper advantage for you in relation to your assessment(s) or deliberately and unnecessarily disadvantages other students. It includes, but it is not limited to plagiarism, collusion and contract cheating.

[Student Appeals](https://studenthub.city.ac.uk/help-and-support/extenuating-circumstances-complaints-appeals): The appeals process is intended for the very rare cases where no resolution or remedy was possible at an earlier stage (i.e. prior to the Assessment Board approving the results of taught students or a decision being made regarding the registration status or examination results of research students).

[Student Union Advise](https://csgsu.co.uk/advice-and-support): It is likely that if things go wrong, the University will refer you to Union Advice for advice: your first step should be to contact us to make an appointment. Please find more information from the link: [Advice and Support](https://csgsu.co.uk/advice-and-support)

[Progression and Awards](https://studenthub.city.ac.uk/timetabling-term-dates-exams/progression-and-awards) Important information about your assessment results, your programme and the support available to you and details of the timescales if you want to make an appeal.

# Key school contacts
Module Leader is the first point of contact for any queries you may have about the content or organisation of module you are studying. If you are unsure how to approach an assessment or are struggling to understand any parts of the learning materials you have been assigned, please do feel free to email or meet with a module leader to get clarification and support during designated ‘office hours’.
How to contact:   Module leader details will be available on respective Module Moodle Pages
Personal/year group Tutor will act as a mentor and key contact for any type of support you may need. You can talk to your personal tutor about any struggles with your studies and personal life. Your personal tutor also can refer you to the University’s more specialised services for academic, mental health and wellbeing support.  You can discuss your career aspirations with your personal tutor too and receive advice on how to plan your studies accordingly.
How to contact:   Details of student Personal Tutors will be available on Evision, [https://evision.city.ac.uk/](https://evision.city.ac.uk/).
Student Experience Lead has an overview of all operational issues concerning your experience at University. They also act as a second point of contact in case you cannot reach to your personal tutor.
Course Officers are responsible for the administration of the course and official records of students. Your Course Officer will be able to answer questions related to:
- the administration and official records of students.
- Moodle page enrolment
- Program or module change
- Timetabling clash
- how to submit an assessment, or when specific grades will be released.
- advice on extensions to assessment deadlines, submitting an Extenuating circumstance.
- Suspension and interruption of studies if you are struggling with your course
How to contact:  You can contact course office through email or by visiting Course Office information desk in person on weekdays from 10AM – 5PM, in A129, College Building.
Undergraduate Programmes:
Sociology and Criminology [ugsocandcrim@city.ac.uk](mailto:ugsocandcrim@city.ac.uk)
International Politics (inc. History)  [Intpol.ug@city.ac.uk](mailto:Intpol.ug@city.ac.uk)  Economics  [economics.ug@city.ac.uk](mailto:economics.ug@city.ac.uk)
Postgraduate Programmes   [pgspga@city.ac.uk](mailto:pgspga@city.ac.uk)

Student Welfare and Engagement Officers are your first points of contact for any wellbeing or student experience related issues. Some topics which students discuss with Student Engagement Officers can include, but are not limited to;
Stress and anxiety, general wellbeing issues, financial stress, challenging living environments, time-consuming work or caring commitments, and disabilities. Based on the topic either a Student Welfare or Student Engagement Officer will reply to your query and provide advice on how you can best access the support services available to you at the University.  They may also suggest that you meet with them so they can get more details on the support you need. You can book a meeting here [School of Policy and Global Affairs Student Wellbeing Support](https://outlook.office365.com/book/SchoolofPolicyandGlobalAffairsStudentWellbeingSupport@cityuni.onmicrosoft.com/?ae=true&ismsaljsauthenabled=true)
Log a case here for support: [Support@City  · City University of London](https://support.city.ac.uk/create-case/)
If you are experiencing mental health Issues or have a diagnosed mental health condition or disability it is important that you register with the Student Mental Health Services, even if you are currently receiving support externally. The Student Mental Health Service can put in place an individualized Student Support Plan with reasonable adjustments recommendations.  You can complete an e-Referral to the Student Health & Wellbeing service at this link: [Student Health & Wellbeing e-Referral  · City University of London](https://support.city.ac.uk/eReferral/?_gl=1%2A1yf5nzx%2A_gcl_au%2AMTUzMzI5MTY4Ny4xNzQ4NjAxODEy%2A_ga%2ANzcwMjIyODIzLjE3NDA2NTA3Mjg.%2A_ga_YLSK0292X4%2AczE3NTU1OTIyOTkkbzM2MiRnMSR0MTc1NTU5NDg4MCRqMzYkbDAkaDA.) if you would prefer to meet with a Student Health and Wellbeing Engagement Advisor to discuss you can book a meeting here: [Student Health & Wellbeing](https://outlook.office365.com/book/StudentHealthWellbeing@cityuni.onmicrosoft.com/s/fmv9wdkSi0m08PSZBNQghg2?ismsaljsauthenabled=true)
- If you are unable to attend classes for more than seven calendar days due to extenuating circumstances, you may request an Authorised Absence. If approved, the period covered will be formally excluded from your attendance calculations. Absences of seven days or fewer do not require formal approval.
- How to apply:
- Undergraduate students – submit your request through the [SEAtS Mobile App](https://studenthub.citystgeorges.ac.uk/academic-resources/learning-and-study-support/study-skills-and-support/attendance-and-engagement/count-me-in).
- Postgraduate Taught students – apply via the [online Authorised Absence form](https://cityunilondon.eu.qualtrics.com/jfe/form/SV_5hzQmuXfZBM5plk).
- Research students - submission an application via [Research Manager](https://researchmanager.city.ac.uk/do/city-login/login).
- Further guidance on managing absences, including eligibility and evidence requirements, is available on the [Attendance and Engagement](https://studenthub.citystgeorges.ac.uk/academic-resources/learning-and-study-support/study-skills-and-support/attendance-and-engagement)  Student Hub page.

# Student Support services
[Library](https://libraryservices.city.ac.uk/) - provides printed resources, study spaces (for group study, quiet study and individual silent study), networked PCs and wi-fi across five levels.
[Study Spaces](https://studenthub.city.ac.uk/information-technology/citynav) - these spaces include quiet areas for focused work, silent study zones, and more social spaces for collaborative learning. For more information on where to find these Study Spaces, visit [CityNav](https://studenthub.city.ac.uk/information-technology/citynav).
## IT support
If students experience IT issues, a ticket can be logged via [service now](https://www.city.ac.uk/itservicedesk).
Alternatively, students can call the IT help desk on 0207 040 8181 or visit the IT help desk in person where they can help with basic issues such as wi-fi access etc. The helpdesk in located in University Building.

[CityBuddy](https://buddy.city.ac.uk/apply/mentee/) is a second- or third-year student who will mentor a first-year student on their course. They are there to show new students all that City has to offer; answer any questions they may have and provide a valuable insight into studying on the course. [Apply to get a mentor that will be your personal guide to studying at City](https://cityunilondon.eu.qualtrics.com/jfe/form/SV_9M41s2FmiwmYVM2).
[Support@City](https://support.city.ac.uk/create-case/?_gl=1%2asv17k1%2a_ga%2aODU0NDA5NDU1LjE2MjA5ODEyNjI.%2a_ga_YLSK0292X4%2aMTY5NDcwNDk3Ni4xOTcuMS4xNjk0NzA1MDMwLjYuMC4w) - is the online system allowing students to submit and track their queries through a dedicated portal. The platform brings together many of City St George’s student support services in a secure portal to better understand and address students' needs. The system includes the following teams:
[Accommodation](https://studenthub.city.ac.uk/help-and-support/accommodation-student-hub)
- [Uni Cares](https://studenthub.city.ac.uk/help-and-support/city-cares) - City's dedicated support network for care-experienced students, young adult carers, young estranged students, refugees and asylum seekers.
[International Student & Visa Advice](https://studenthub.city.ac.uk/help-and-support/visa-advice-for-international-students)
[Student Funding](https://studenthub.city.ac.uk/help-and-support/student-funding)
[Student Health & Wellbeing](https://studenthub.city.ac.uk/help-and-support/student-health-wellbeing)
[School Student Welfare teams](https://studenthub.city.ac.uk/help-and-support/support-within-your-school)
[Student Support Hub Advisers](https://studenthub.city.ac.uk/help-and-support/student-support-hub-adviser-team)

[The Student Support Hub](https://www.city.ac.uk/about/facilities/specialist-facilities/student-support-hub) - (located in Level 1, Drysdale Building) is designed to provide in-person access to a wide range of essential student support services. The Student Support Hub will operate from 9:00am to 6:30pm during term time. Along with general enquiries, you can visit the following support services:
- [Academic English support](https://studenthub.city.ac.uk/help-and-support/english-for-academic-purposes) - academic writing and English language support for international students and for students whose first language is not English.
- [Academic Skills](https://studenthub.city.ac.uk/help-and-support/improve-your-study-skills) – runs workshops, webinars and one-to-one support sessions to help you to become a more effective learner.
- [Accommodation](https://studenthub.city.ac.uk/help-and-support/accommodation-student-hub) - can help with the application process, any queries regarding the rooms, halls, fees and contracts, support if you are looking for accommodation during the academic year, viewing halls and much more.
- [Careers & Employability](https://studenthub.city.ac.uk/careers-and-employability) - encompass careers, employability, and student development activities, including careers resources and appointments, skills sessions, employer events, community volunteering, professional mentoring, the Micro-Placement Programme and the City Buddies scheme.
- [Uni Cares](https://studenthub.city.ac.uk/help-and-support/city-cares) - City's dedicated support network for care-experienced students, young adult carers, young estranged students, refugees and asylum seekers.
- [Digital Skills](https://studenthub.city.ac.uk/help-and-support/studying-online/digital-skills-and-support) - supports you to effectively use digital technologies and incorporate them into your learning, student experience and employability.
- [International Student & Visa Advice](https://studenthub.city.ac.uk/help-and-support/visa-advice-for-international-students/responsibilities) - provides confidential advice and guidance to applicants and students on study-related visa and immigration issues.
- [IT Service Desk](https://studenthub.citystgeorges.ac.uk/student-support-services/it-services) - is the first point of contact for all IT queries.
- [Student Funding](https://studenthub.city.ac.uk/help-and-support/student-funding) - provides advice on student funding available to support your studies at City.
- [Student Health & Wellbeing](https://studenthub.city.ac.uk/help-and-support/student-health-wellbeing) - provides practical, emotional and specialist disability related support to our students.
- [Student Support Hub Advisers](https://studenthub.city.ac.uk/help-and-support/student-support-hub-adviser-team)
- Production of ID cards - expired, lost/stolen, new (outside of the main registration period)
- Production of a range of letters, student status, bank letter, Schengen visa letter
- Help with 18+ oyster card application
- Signing of railcard documents
- Registration (outside of the main registration period)
- Updating student details
- Collection point for graduation certificates

[Togetherall](https://studenthub.city.ac.uk/help-and-support/student-health-wellbeing/togetherall)  - is a safe, online peer support community where you can get and give support to improve your mental health and wellbeing. The community is moderated 24/7 by mental health professionals ensuring the safety and anonymity of all members.

[The Report+Support platform](https://reportandsupport.city.ac.uk/) - provides staff and students with a confidential way to report instances of unacceptable behaviour, such as bullying, harassment, discrimination, hate incidents, domestic abuse, or sexual violence. Whether you have personally experienced these behaviours or have witnessed them happening to someone else, the platform offers a straightforward and accessible way to report your concerns.

[Stay City Safe](https://studenthub.city.ac.uk/help-and-support/stay-city-safe) initiative provides you with essential information on what to do in case of an incident, how to report it, and where to seek assistance. You can download our safety booklet: [Your guide to staying safe in London](https://studenthub.city.ac.uk/__data/assets/pdf_file/0006/814416/3748-Stay-City-Safe-booklet-AL1i-digital-1.pdf)

# [Student’s Union](https://www.csgsu.co.uk/)
City St George’s, University of London Students' Union is a membership-led organisation, independent of the University, which exists to make sure you have the best overall experience at City both socially and academically. The Union is in Level 2 of the Student Support Hub in Drysdale Building.
SU offers:
- [Union advice](https://csgsu.co.uk/advice-and-support) - on academic appeals, academic misconduct, complaints, extenuating circumstances and more.
- [Student Societies](https://csgsu.co.uk/explore-and-join/societies) - are groups created, run and lead by students for students. These can be hobbies, campaigns, cultural, academic, basically anything you can think of.  Any student can join a society. Joining a society is super easy through our website, just click on any society you are interested in and purchase the standard membership (even if it is free)!
- [Start a new society](https://csgsu.co.uk/explore-and-join/start-or-adopt-a-group) Any student at City St George's can apply to set up a new student group. Setting up a new student group equips you with employability skills including; leadership, teamwork, communication and events planning.  When you have a society idea and your committee together, please fill out [the form here](https://csgsu.co.uk/explore-and-join/start-or-adopt-a-group)!
- [SU Events](https://events.csgsu.co.uk/)
- [Sports](https://csgsu.co.uk/sports)
- [Short Term Loans](https://csgsu.co.uk/advice-and-support/finances) – Interest free loans of up to £200.
- [Program rep training](https://csgsu.co.uk/your-voice/programme-and-year-representatives)
[Become a Program rep](https://csgsu.co.uk/your-voice/programme-and-year-representatives). You are invited to nominate yourself to become a Program rep. Programme Reps play a key role in ensuring that all students have a voice and an opportunity to share feedback about their learning experience. They help students make as many positive changes as possible and ultimately, help improve the quality of education at City St George’s.
You can nominate yourself by submitting [the nomination form](https://forms.office.com/e/6MEdG2EStU) by Wednesday, October 15, 2025.
You can find more information from [Programme Reps (csgsu.co.uk)](https://csgsu.co.uk/your-voice/programme-and-year-representatives).
For any questions or queries, email studentrep@city.ac.uk or visit SU Welcome Desk in Student Support Hub!

# [Careers & Employability](https://studenthub.city.ac.uk/careers-and-employability)
Year 2 students can apply to the SPGA Placement and Exchange Programmes:
## SPGA Placement Programme
## SPGA Exchange Programme

Careers & Employability team encompasses careers, employability, and student development activities, including careers resources and appointments, skills sessions, employer events, community volunteering, professional mentoring, the Micro-Placement Programme and the City Buddies scheme. Our resourceful careers team can offer expertise and support, to assist you in developing your career prospects whilst at City, and beyond.

- [Careers Hub](https://careershub.city.ac.uk/s/resources) has everything you need to start your career journey. Each section has a list of key information for that topic and links to documents and websites on the subject.
- [Careers Fairs and employer events](https://careershub.city.ac.uk/students/events)
- [Micro-Placements](https://studenthub.city.ac.uk/careers-and-employability/micro-placements-programme) are an exciting way to gain professional experience via short summer placements with a wide range of UK-based employers for year 1 and 2 UG students. The deadline for application is 12:00 noon on Monday 14 October 2024.
- The [Professional Mentoring Scheme](https://studenthub.citystgeorges.ac.uk/career-development/professional-mentoring-scheme) is a six-month programme that pairs students with industry professionals in order to develop their skills, confidence and future employability. The deadline for application is 23:59, Sunday, October 6th, 2024.
- [Unitemps](https://www.unitemps.com/) - City St George’s in-house temporary jobs agency which offers part time paid temporary work in and around the University for students and graduates: You can sign up and apply for roles on the [Unitemps website](https://www.unitemps.com/).
- [Student Ambassador scheme](https://studenthub.city.ac.uk/careers-and-employability/student-ambassador-scheme). Develop your skills, make friends and earn some extra money by becoming a Student Ambassador at City St George’s!
- [Book a Career appointment](https://careershub.city.ac.uk/students/appointments/topics?campusId=704). The best way to think about your career is in conversation with one of our expert career consultants. They can respond directly to your questions and concerns and help give you direction, even if you are not sure of exactly what career path you want to follow.

# Other useful information
[Registration](https://studenthub.city.ac.uk/student-administration/registration) - all new and returning students of City, University of London are required to register for their course each year. If you have any other questions regarding registration, please email the [Registration team](mailto:registration@city.ac.uk)
If you think you may be late completing registration and need more time, please contact the Course Officer for your course within your Department as this will need to be considered by your academic Course Director.

[Fees and Finance](https://studenthub.city.ac.uk/student-administration/fees-and-finance)- financial information for students who are studying at City St George’s, University of London.

[Evision-Get Official Letters and Pay Fees](https://evision.city.ac.uk/?_gl=1*7eeo8m*_ga*NjM2MTY1Mjk3LjE2NjY3MTIwOTU.*_ga_YLSK0292X4*MTY5NDUxMTg4OS4xNC4xLjE2OTQ1MTIxMjkuNjAuMC4w). You may need a proof of study letter for various things such as council tax exemption, registering with a doctors surgery, or even opening a student bank account. You can produce some of these documents yourselves by logging into Evision with their student details.

[CitySport](https://www.citysport.org.uk/) - manages the high-quality sport facilities at CitySport and deliver a range of health, fitness, and wellbeing initiatives across the University.
[Faith, belief and culture at City St George's](https://studenthub.citystgeorges.ac.uk/student-support-services/faith-and-cultural-support)

For International Students:
- [Health information](https://studenthub.city.ac.uk/help-and-support/your-health)
- [International Student & Visa Advice](https://studenthub.city.ac.uk/help-and-support/visa-advice-for-international-students) - advice and guidance to applicants and students on study-related visa and immigration issues.

You can find more information about student services from [Help and support | Student Hub | City, University of London](https://studenthub.city.ac.uk/help-and-support)

# Resources for staff
[Toolkit for Supporting Students](https://cityuni.sharepoint.com/sites/cs_Supportingyourstudents): includes resources, guidance and signposting to aid you in supporting students. Useful information and links for all staff, [personal tutors](https://cityuni.sharepoint.com/sites/cs_Supportingyourstudents/SitePages/Guidance-for-personal-tutors.aspx), course officers and school support staff.

## [Wellbeing & Mental Health E-Learning](https://staffhub.city.ac.uk/develop-at-city/wellbeing-at-city-hub/wellbeing-and-mental-health-e-learning)
City has collaborated with Charlie Waller Trust, the UK mental health charity, to create a series of e-learning courses aimed at equipping staff with a baseline knowledge of mental health awareness to help themselves, other members of staff and our students. These modules also signpost to key university teams and resources that can further support with wellbeing and mental health.
Course 1: [Staff Supporting Students](https://elearning.charliewaller.org/course-details/681ed6fc-46e1-4753-8a18-21063ad94f1f)
Course 2: [Managers Supporting Staff](https://elearning.charliewaller.org/course-details/630cf33e-725b-4d3e-948e-2fcd279e400d)
Course 3: [Wellbeing Strategies](https://elearning.charliewaller.org/course-details/655f3612-b251-4001-a3a1-5d9106e67491)
Course 4:[Risks and Crises](https://elearning.charliewaller.org/course-details/ed3f83c6-5a72-440d-9bc4-6d26966e15a7)

## [Attendance and Engagement Monitoring](https://cityuni.sharepoint.com/sites/CSGMerger/Files/Forms/AllItems.aspx?id=%2Fsites%2FCSGMerger%2FFiles%2FDocuments%2FAttendance%20and%20monitoring%20changes%20for%202025%2D26%2Epdf&parent=%2Fsites%2FCSGMerger%2FFiles%2FDocuments)
Undergraduate students can download a new [SEAtS Mobile App](https://studenthub.citystgeorges.ac.uk/academic-resources/learning-and-study-support/study-skills-and-support/attendance-and-engagement/count-me-in) through which they will be able to view their timetable, view their attendance information, submit authorised absences requests and receive updates on class/timetable changes.
Academic staff can view students’ overall attendance per module, monitor absences and lateness, as well as run reports by programme and module through SEAtS.
We ask that all colleagues involved in teaching engage with this system to support student attendance. Log into [SEAtS](https://staffcommunications.newsweaver.com/1cuay0lb4l/yzpv63vjgnc1ttzyvuq1bs/external?email=true&a=5&p=5297842&t=217120) via Single Sign On to access this data. You can [find out more about SEAtS attendance and monitoring training here](https://staffcommunications.newsweaver.com/1cuay0lb4l/5u2ufkq6fke1ttzyvuq1bs/external?email=true&a=5&p=5297842&t=217120).

## Transition for Academic Success Programme
The Transition for Academic Success Programme aims to address the unique academic challenges faced by first year students when transitioning from secondary education or when returning to Higher Education from employment. The programme of online modules, which will run throughout terms 1 and 2, has been fully co-created with students who have helped identify the topics and areas of focus.
You can find more information [including Powerpoint slides to incorporate into Induction activities, as well as more information on programme content on the Learning and Teaching Hub](https://staffcommunications.newsweaver.com/1cuay0lb4l/jigmhvwn6171ttzyvuq1bs/external?email=true&a=5&p=5297842&t=217120).

